### PR TITLE
Fix inline event handlers

### PR DESCRIPTION
**Pull request by nikcorg**
Certain markup with inline event handlers would fail to render with postscribe. (See https://github.com/krux/postscribe/issues/134 for further discussion). This PR, while maybe not the most elegant, proposes a fix to the problem.

The solution extracts the offending attribute contents into a global function and replaces the original attribute contents in the final rendering with a function call.

The function exporter is configurable. A default exporter is included. Unfortunately, for the moment, the export _must_ be global.

Time allowing, I might try and squeeze in a patch to customise the export target to avoid global pollution.

### CODE REVIEW

**Comment by nikcorg** [comment]
Let me know what you think, @Ambroos.

**Comment by nikcorg** [comment]
Is this repository still alive? I sent the PR here, because it had evidence of life more recently than the upstream repository. But was I overly optimistic?

**Comment by Ambroos** [comment]
Still alive, sorry for the delay!

I'm not that good with the internals of Postscribe, but as long as tests pass I'll accept it. Give me a few minutes to do some internal tests too and then I'll merge and release a new version to NPM.

**Comment by Ambroos** [comment]
@nikcorg Thanks for your contribution! A new release is up on NPM as `postscribe-umd`. With your next contribution, please don't include compiled/dist changes as those can lead to merge conflicts and have to be regenerated for a release anyway.

**Comment by nikcorg** [comment]
Great. thanks! Duly noted, I will skip the build step on subsequent PR's :-)

**Pull request merged**
